apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 2  # Deploy two replicas for high availability
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: laghavendrasinghparmar/nodeapp  # Replace with your actual image name
        ports:
        - containerPort: 8000  # Assuming the Node.js app listens on port 8000
