apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80  # Expose the service on port 80
    targetPort: 8000  # Forward traffic to the container port

